"""
sql_validator.py
------------------
Validates that a SQL string generated by the AI is safe to run: a
single, read-only SELECT statement, with no other statement types and
no comment-based tricks for hiding a second statement.

This is a defense-in-depth layer. The system prompt in prompts.py
already instructs the LLM to only produce SELECT statements — this
module is what actually enforces it before anything touches the
database, so a prompt-injection attempt or a model mistake can't slip
a destructive statement through.

Usage:
    is_safe, reason = validate_sql(sql_query)
    if not is_safe:
        # show `reason` to the user, do not execute
"""

import re

# Keywords that indicate the query would modify data/schema or do
# something outside a plain read-only SELECT. Checked as whole words
# (case-insensitive) so e.g. "UPDATE" won't false-positive on a column
# literally named "updated_at".
FORBIDDEN_KEYWORDS = [
    "DROP", "DELETE", "UPDATE", "INSERT", "ALTER", "TRUNCATE",
    "CREATE", "GRANT", "REVOKE", "REPLACE", "MERGE", "CALL",
    "EXEC", "EXECUTE", "COPY", "VACUUM", "ATTACH", "DETACH",
    "PRAGMA", "LOCK", "UNLOCK", "SET",
]

_FORBIDDEN_PATTERN = re.compile(
    r"\b(" + "|".join(FORBIDDEN_KEYWORDS) + r")\b",
    re.IGNORECASE,
)

# Matches `--` line comments and `/* ... */` block comments, which we
# strip before checking so they can't be used to hide a second
# statement or a forbidden keyword from the checks above (while still
# having it interpreted by the database).
_LINE_COMMENT = re.compile(r"--.*?(\n|$)")
_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)


class SQLValidationError(Exception):
    """Raised by validate_sql_or_raise() when a query fails validation."""


def _strip_comments(sql: str) -> str:
    sql = _BLOCK_COMMENT.sub(" ", sql)
    sql = _LINE_COMMENT.sub(" ", sql)
    return sql


def validate_sql(sql: str) -> tuple[bool, str]:
    """
    Check whether `sql` is safe to execute.

    Returns:
        (True, "") if the query passes all checks.
        (False, reason) if it fails, where `reason` is a short,
        user-facing explanation of what's wrong.
    """
    if not sql or not sql.strip():
        return False, "No SQL query was generated."

    cleaned = _strip_comments(sql).strip()

    if not cleaned:
        return False, "Query contained only comments — nothing to execute."

    # Only one trailing semicolon is allowed (or none). Anything else
    # means multiple statements are chained together.
    body = cleaned[:-1] if cleaned.endswith(";") else cleaned
    if ";" in body:
        return False, (
            "Only a single SQL statement is allowed. This query appears "
            "to contain multiple statements separated by semicolons."
        )

    if not re.match(r"^\s*SELECT\b", body, re.IGNORECASE):
        return False, "Only SELECT statements are allowed."

    forbidden_match = _FORBIDDEN_PATTERN.search(body)
    if forbidden_match:
        return False, (
            f"Query contains a disallowed keyword: {forbidden_match.group(0).upper()}. "
            "Only read-only SELECT queries are permitted."
        )

    return True, ""


def validate_sql_or_raise(sql: str) -> None:
    """Same check as validate_sql(), but raises SQLValidationError
    instead of returning a tuple — convenient for call sites that want
    to use a try/except instead of an if-check."""
    is_safe, reason = validate_sql(sql)
    if not is_safe:
        raise SQLValidationError(reason)


if __name__ == "__main__":
    # Quick manual tests: run `python sql_validator.py`.
    test_cases = [
        "SELECT * FROM customers;",
        "SELECT customer_id, full_name FROM customers WHERE city = 'Bengaluru'",
        "DROP TABLE customers;",
        "SELECT * FROM customers; DROP TABLE customers;",
        "UPDATE customers SET city = 'Nowhere';",
        "SELECT * FROM customers -- ; DROP TABLE customers;",
        "SELECT updated_at FROM orders",  # should PASS — not a real UPDATE
        "",
    ]
    for sql in test_cases:
        ok, reason = validate_sql(sql)
        status = "✅ SAFE" if ok else f"❌ BLOCKED ({reason})"
        print(f"{status}\n  SQL: {sql!r}\n")
